/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sigmaPoolProxySol from "./SigmaPoolProxy.sol";
export type { sigmaPoolProxySol };
export type { SigmaAction } from "./SigmaAction";
