/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ISigmaActionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "sigmaAddFundWithAction"
      | "sigmaQueueWithdraw"
      | "sigmaVerifyAndRedeemToken"
      | "sigmaWithdrawFund"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "sigmaAddFundWithAction",
    values: [AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaQueueWithdraw",
    values: [string, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaVerifyAndRedeemToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaWithdrawFund",
    values: [string, AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "sigmaAddFundWithAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sigmaQueueWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sigmaVerifyAndRedeemToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sigmaWithdrawFund",
    data: BytesLike
  ): Result;
}

export interface ISigmaAction extends BaseContract {
  connect(runner?: ContractRunner | null): ISigmaAction;
  waitForDeployment(): Promise<this>;

  interface: ISigmaActionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  sigmaAddFundWithAction: TypedContractMethod<
    [
      _clientAddress: AddressLike,
      _tokenAddress: AddressLike,
      _tokenValue: BigNumberish,
      _data: string
    ],
    [boolean],
    "nonpayable"
  >;

  sigmaQueueWithdraw: TypedContractMethod<
    [
      _ticketId: string,
      _clientAddress: AddressLike,
      _tokenAddress: AddressLike,
      _tokenValue: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  sigmaVerifyAndRedeemToken: TypedContractMethod<
    [
      _clientAddress: AddressLike,
      _tokenAddress: AddressLike,
      _redeemValue: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  sigmaWithdrawFund: TypedContractMethod<
    [
      _ticketId: string,
      _clientAddress: AddressLike,
      _tokenAddress: AddressLike,
      _tokenValue: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "sigmaAddFundWithAction"
  ): TypedContractMethod<
    [
      _clientAddress: AddressLike,
      _tokenAddress: AddressLike,
      _tokenValue: BigNumberish,
      _data: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sigmaQueueWithdraw"
  ): TypedContractMethod<
    [
      _ticketId: string,
      _clientAddress: AddressLike,
      _tokenAddress: AddressLike,
      _tokenValue: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sigmaVerifyAndRedeemToken"
  ): TypedContractMethod<
    [
      _clientAddress: AddressLike,
      _tokenAddress: AddressLike,
      _redeemValue: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sigmaWithdrawFund"
  ): TypedContractMethod<
    [
      _ticketId: string,
      _clientAddress: AddressLike,
      _tokenAddress: AddressLike,
      _tokenValue: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
