/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SigmaPoolV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "addWorkers"
      | "changeSigmaActionContract"
      | "changeSigmaPool"
      | "getClientSigmaNonce"
      | "getLiquidityAmountInPool"
      | "getSatisTokenAmountInContract"
      | "getSigmaPoolAddress"
      | "getSigmaPoolOwner"
      | "removeWorkers"
      | "sigmaActionContractAddress"
      | "sigmaAddFundWithAction"
      | "sigmaOwner"
      | "sigmaPoolAddressList"
      | "sigmaProxyWorkerList"
      | "sigmaVerifyAndPartialWithdrawFund"
      | "sigmaVerifyAndQueue"
      | "sigmaVerifyAndRedeemToken"
      | "sigmaVerifyAndWithdrawFund"
      | "transferOwnershipSigmaPoolProxy"
      | "verifySigmaProxyWorker"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddWorkers"
      | "ChangeOwnership"
      | "ChangePoolAddress"
      | "RemoveWorkers"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addWorkers",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "changeSigmaActionContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeSigmaPool",
    values: [string[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getClientSigmaNonce",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityAmountInPool",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSatisTokenAmountInContract",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSigmaPoolAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSigmaPoolOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeWorkers",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaActionContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaAddFundWithAction",
    values: [AddressLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaPoolAddressList",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaProxyWorkerList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaVerifyAndPartialWithdrawFund",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaVerifyAndQueue",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaVerifyAndRedeemToken",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sigmaVerifyAndWithdrawFund",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnershipSigmaPoolProxy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySigmaProxyWorker",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addWorkers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeSigmaActionContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeSigmaPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClientSigmaNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityAmountInPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSatisTokenAmountInContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSigmaPoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSigmaPoolOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeWorkers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sigmaActionContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sigmaAddFundWithAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sigmaOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sigmaPoolAddressList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sigmaProxyWorkerList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sigmaVerifyAndPartialWithdrawFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sigmaVerifyAndQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sigmaVerifyAndRedeemToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sigmaVerifyAndWithdrawFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnershipSigmaPoolProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySigmaProxyWorker",
    data: BytesLike
  ): Result;
}

export namespace AddWorkersEvent {
  export type InputTuple = [addWorkerList: AddressLike[]];
  export type OutputTuple = [addWorkerList: string[]];
  export interface OutputObject {
    addWorkerList: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChangeOwnershipEvent {
  export type InputTuple = [newAdminAddress: AddressLike];
  export type OutputTuple = [newAdminAddress: string];
  export interface OutputObject {
    newAdminAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChangePoolAddressEvent {
  export type InputTuple = [newlyAddedPoolAddressList: AddressLike[]];
  export type OutputTuple = [newlyAddedPoolAddressList: string[]];
  export interface OutputObject {
    newlyAddedPoolAddressList: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoveWorkersEvent {
  export type InputTuple = [removeWorkerList: AddressLike[]];
  export type OutputTuple = [removeWorkerList: string[]];
  export interface OutputObject {
    removeWorkerList: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SigmaPoolV2 extends BaseContract {
  connect(runner?: ContractRunner | null): SigmaPoolV2;
  waitForDeployment(): Promise<this>;

  interface: SigmaPoolV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addWorkers: TypedContractMethod<
    [_addWorkerList: AddressLike[]],
    [void],
    "nonpayable"
  >;

  changeSigmaActionContract: TypedContractMethod<
    [_newActionContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  changeSigmaPool: TypedContractMethod<
    [_newPoolNameList: string[], _newPoolAddressList: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getClientSigmaNonce: TypedContractMethod<
    [_clientAddress: AddressLike, _poolName: string],
    [bigint],
    "view"
  >;

  getLiquidityAmountInPool: TypedContractMethod<
    [_tokenAddress: AddressLike, _poolName: string],
    [bigint],
    "view"
  >;

  getSatisTokenAmountInContract: TypedContractMethod<
    [_tokenAddress: AddressLike, _poolName: string],
    [bigint],
    "view"
  >;

  getSigmaPoolAddress: TypedContractMethod<
    [_poolName: string],
    [string],
    "view"
  >;

  getSigmaPoolOwner: TypedContractMethod<[_poolName: string], [string], "view">;

  removeWorkers: TypedContractMethod<
    [_removeWorkerList: AddressLike[]],
    [void],
    "nonpayable"
  >;

  sigmaActionContractAddress: TypedContractMethod<[], [string], "view">;

  sigmaAddFundWithAction: TypedContractMethod<
    [
      _tokenAddress: AddressLike,
      _tokenValue: BigNumberish,
      _data: string,
      _poolName: string
    ],
    [boolean],
    "nonpayable"
  >;

  sigmaOwner: TypedContractMethod<[], [string], "view">;

  sigmaPoolAddressList: TypedContractMethod<[arg0: string], [string], "view">;

  sigmaProxyWorkerList: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  sigmaVerifyAndPartialWithdrawFund: TypedContractMethod<
    [
      _targetSignature: BytesLike,
      _tokenAddress: AddressLike,
      _partialWithdrawValue: BigNumberish,
      _tier: BigNumberish,
      _nonce: BigNumberish,
      _poolName: string
    ],
    [boolean],
    "nonpayable"
  >;

  sigmaVerifyAndQueue: TypedContractMethod<
    [
      _targetSignature: BytesLike,
      _tokenAddress: AddressLike,
      _queueValue: BigNumberish,
      _tier: BigNumberish,
      _nonce: BigNumberish,
      _poolName: string
    ],
    [boolean],
    "nonpayable"
  >;

  sigmaVerifyAndRedeemToken: TypedContractMethod<
    [
      _targetSignature: BytesLike,
      _tokenAddress: AddressLike,
      _redeemValue: BigNumberish,
      _tier: BigNumberish,
      _nonce: BigNumberish,
      _poolName: string
    ],
    [boolean],
    "nonpayable"
  >;

  sigmaVerifyAndWithdrawFund: TypedContractMethod<
    [
      _targetSignature: BytesLike,
      _tokenAddress: AddressLike,
      _withdrawValue: BigNumberish,
      _tier: BigNumberish,
      _nonce: BigNumberish,
      _poolName: string
    ],
    [boolean],
    "nonpayable"
  >;

  transferOwnershipSigmaPoolProxy: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifySigmaProxyWorker: TypedContractMethod<
    [_workerAddress: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addWorkers"
  ): TypedContractMethod<[_addWorkerList: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeSigmaActionContract"
  ): TypedContractMethod<
    [_newActionContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeSigmaPool"
  ): TypedContractMethod<
    [_newPoolNameList: string[], _newPoolAddressList: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClientSigmaNonce"
  ): TypedContractMethod<
    [_clientAddress: AddressLike, _poolName: string],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLiquidityAmountInPool"
  ): TypedContractMethod<
    [_tokenAddress: AddressLike, _poolName: string],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSatisTokenAmountInContract"
  ): TypedContractMethod<
    [_tokenAddress: AddressLike, _poolName: string],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSigmaPoolAddress"
  ): TypedContractMethod<[_poolName: string], [string], "view">;
  getFunction(
    nameOrSignature: "getSigmaPoolOwner"
  ): TypedContractMethod<[_poolName: string], [string], "view">;
  getFunction(
    nameOrSignature: "removeWorkers"
  ): TypedContractMethod<
    [_removeWorkerList: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sigmaActionContractAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sigmaAddFundWithAction"
  ): TypedContractMethod<
    [
      _tokenAddress: AddressLike,
      _tokenValue: BigNumberish,
      _data: string,
      _poolName: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sigmaOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sigmaPoolAddressList"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "sigmaProxyWorkerList"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "sigmaVerifyAndPartialWithdrawFund"
  ): TypedContractMethod<
    [
      _targetSignature: BytesLike,
      _tokenAddress: AddressLike,
      _partialWithdrawValue: BigNumberish,
      _tier: BigNumberish,
      _nonce: BigNumberish,
      _poolName: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sigmaVerifyAndQueue"
  ): TypedContractMethod<
    [
      _targetSignature: BytesLike,
      _tokenAddress: AddressLike,
      _queueValue: BigNumberish,
      _tier: BigNumberish,
      _nonce: BigNumberish,
      _poolName: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sigmaVerifyAndRedeemToken"
  ): TypedContractMethod<
    [
      _targetSignature: BytesLike,
      _tokenAddress: AddressLike,
      _redeemValue: BigNumberish,
      _tier: BigNumberish,
      _nonce: BigNumberish,
      _poolName: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sigmaVerifyAndWithdrawFund"
  ): TypedContractMethod<
    [
      _targetSignature: BytesLike,
      _tokenAddress: AddressLike,
      _withdrawValue: BigNumberish,
      _tier: BigNumberish,
      _nonce: BigNumberish,
      _poolName: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnershipSigmaPoolProxy"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifySigmaProxyWorker"
  ): TypedContractMethod<[_workerAddress: AddressLike], [boolean], "view">;

  getEvent(
    key: "AddWorkers"
  ): TypedContractEvent<
    AddWorkersEvent.InputTuple,
    AddWorkersEvent.OutputTuple,
    AddWorkersEvent.OutputObject
  >;
  getEvent(
    key: "ChangeOwnership"
  ): TypedContractEvent<
    ChangeOwnershipEvent.InputTuple,
    ChangeOwnershipEvent.OutputTuple,
    ChangeOwnershipEvent.OutputObject
  >;
  getEvent(
    key: "ChangePoolAddress"
  ): TypedContractEvent<
    ChangePoolAddressEvent.InputTuple,
    ChangePoolAddressEvent.OutputTuple,
    ChangePoolAddressEvent.OutputObject
  >;
  getEvent(
    key: "RemoveWorkers"
  ): TypedContractEvent<
    RemoveWorkersEvent.InputTuple,
    RemoveWorkersEvent.OutputTuple,
    RemoveWorkersEvent.OutputObject
  >;

  filters: {
    "AddWorkers(address[])": TypedContractEvent<
      AddWorkersEvent.InputTuple,
      AddWorkersEvent.OutputTuple,
      AddWorkersEvent.OutputObject
    >;
    AddWorkers: TypedContractEvent<
      AddWorkersEvent.InputTuple,
      AddWorkersEvent.OutputTuple,
      AddWorkersEvent.OutputObject
    >;

    "ChangeOwnership(address)": TypedContractEvent<
      ChangeOwnershipEvent.InputTuple,
      ChangeOwnershipEvent.OutputTuple,
      ChangeOwnershipEvent.OutputObject
    >;
    ChangeOwnership: TypedContractEvent<
      ChangeOwnershipEvent.InputTuple,
      ChangeOwnershipEvent.OutputTuple,
      ChangeOwnershipEvent.OutputObject
    >;

    "ChangePoolAddress(address[])": TypedContractEvent<
      ChangePoolAddressEvent.InputTuple,
      ChangePoolAddressEvent.OutputTuple,
      ChangePoolAddressEvent.OutputObject
    >;
    ChangePoolAddress: TypedContractEvent<
      ChangePoolAddressEvent.InputTuple,
      ChangePoolAddressEvent.OutputTuple,
      ChangePoolAddressEvent.OutputObject
    >;

    "RemoveWorkers(address[])": TypedContractEvent<
      RemoveWorkersEvent.InputTuple,
      RemoveWorkersEvent.OutputTuple,
      RemoveWorkersEvent.OutputObject
    >;
    RemoveWorkers: TypedContractEvent<
      RemoveWorkersEvent.InputTuple,
      RemoveWorkersEvent.OutputTuple,
      RemoveWorkersEvent.OutputObject
    >;
  };
}
